/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'condorauth',
    path: '/condorauth',
    component: 'layout.base',
    meta: {
      title: 'condorauth',
      i18nKey: 'route.condorauth'
    },
    children: [
      {
        name: 'condorauth_user',
        path: '/condorauth/user',
        component: 'view.condorauth_user',
        meta: {
          title: 'condorauth_user',
          i18nKey: 'route.condorauth_user'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system'
    },
    children: [
      {
        name: 'system_admin',
        path: '/system/admin',
        component: 'view.system_admin',
        meta: {
          title: 'system_admin',
          i18nKey: 'route.system_admin'
        }
      },
      {
        name: 'system_admin-log',
        path: '/system/admin-log',
        component: 'view.system_admin-log',
        meta: {
          title: 'system_admin-log',
          i18nKey: 'route.system_admin-log'
        }
      },
      {
        name: 'system_attachment',
        path: '/system/attachment',
        component: 'view.system_attachment',
        meta: {
          title: 'system_attachment',
          i18nKey: 'route.system_attachment'
        }
      },
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config'
        }
      },
      {
        name: 'system_crontab',
        path: '/system/crontab',
        component: 'view.system_crontab',
        meta: {
          title: 'system_crontab',
          i18nKey: 'route.system_crontab'
        }
      },
      {
        name: 'system_crud',
        path: '/system/crud',
        component: 'view.system_crud',
        meta: {
          title: 'system_crud',
          i18nKey: 'route.system_crud'
        }
      },
      {
        name: 'system_dict-type',
        path: '/system/dict-type',
        component: 'view.system_dict-type',
        meta: {
          title: 'system_dict-type',
          i18nKey: 'route.system_dict-type'
        }
      },
      {
        name: 'system_login-log',
        path: '/system/login-log',
        component: 'view.system_login-log',
        meta: {
          title: 'system_login-log',
          i18nKey: 'route.system_login-log'
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu'
        }
      },
      {
        name: 'system_profile',
        path: '/system/profile',
        component: 'view.system_profile',
        meta: {
          title: 'system_profile',
          i18nKey: 'route.system_profile'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_test',
        path: '/system/test',
        component: 'view.system_test',
        meta: {
          title: 'system_test',
          i18nKey: 'route.system_test'
        }
      }
    ]
  }
];
